AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  RecognizeImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ocr/
      Handler: app.handler
      Runtime: nodejs8.10
      Events:
        RecognizeImage:
          Type: Api
          Properties:
            Path: /ocr
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RecognizeImageApi:
    Description: "API Gateway endpoint URL for Prod stage for RecognizeImageFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ocr/"
  RecognizeImageFunction:
    Description: "RecognizeImageFunction Lambda Function ARN"
    Value: !GetAtt RecognizeImageFunction.Arn
  RecognizeImageFunctionIamRole:
    Description: "Implicit IAM Role created for RecognizeImageFunction"
    Value: !GetAtt RecognizeImageFunction.Arn
